# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (diff_team_penalty_area_touches_avg_last_15_matches IS cluster1) AND (diff_team_momentum_sum_avg_last_15_matches IS cluster1) AND (diff_team_score_xG_sum_last_15_matches IS cluster1) AND (diff_team_momentum_sum_sum_last_7_matches IS cluster1) AND (diff_team_attacking_third_touches_avg_last_13_matches IS cluster1) AND (diff_team_momentum_sum_sum_last_9_matches IS cluster1) AND (diff_team_momentum_sum_avg_last_11_matches IS cluster1) AND (diff_team_penalty_area_touches_sum_last_7_matches IS cluster1) AND (diff_team_carries_into_the_penalty_area_sum_last_15_matches IS cluster1) AND (diff_team_penalty_area_touches_avg_last_13_matches IS cluster1) AND (diff_team_points_sum_last_15_matches IS cluster1) AND (diff_team_points_sum_last_13_matches IS cluster1) AND (diff_team_momentum_count_avg_last_7_matches IS cluster1) AND (diff_team_shots_on_target_avg_last_13_matches IS cluster1) AND (diff_team_carries_into_the_penalty_area_sum_last_13_matches IS cluster1) AND (diff_team_attacking_third_touches_sum_last_11_matches IS cluster1) AND (diff_team_momentum_sum_avg_last_13_matches IS cluster1) AND (diff_team_score_xG_avg_last_9_matches IS cluster1) AND (diff_team_score_xG_sum_last_13_matches IS cluster1) AND (diff_team_progressive_passes_sum_last_11_matches IS cluster1) AND (diff_team_score_xG_avg_last_7_matches IS cluster1) AND (diff_team_attacking_third_touches_sum_last_15_matches IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (diff_team_penalty_area_touches_avg_last_15_matches IS cluster2) AND (diff_team_momentum_sum_avg_last_15_matches IS cluster2) AND (diff_team_score_xG_sum_last_15_matches IS cluster2) AND (diff_team_momentum_sum_sum_last_7_matches IS cluster2) AND (diff_team_attacking_third_touches_avg_last_13_matches IS cluster2) AND (diff_team_momentum_sum_sum_last_9_matches IS cluster2) AND (diff_team_momentum_sum_avg_last_11_matches IS cluster2) AND (diff_team_penalty_area_touches_sum_last_7_matches IS cluster2) AND (diff_team_carries_into_the_penalty_area_sum_last_15_matches IS cluster2) AND (diff_team_penalty_area_touches_avg_last_13_matches IS cluster2) AND (diff_team_points_sum_last_15_matches IS cluster2) AND (diff_team_momentum_count_avg_last_7_matches IS cluster2) AND (diff_team_shots_on_target_avg_last_13_matches IS cluster2) AND (diff_team_carries_into_the_penalty_area_sum_last_13_matches IS cluster2) AND (diff_team_attacking_third_touches_sum_last_11_matches IS cluster2) AND (diff_team_momentum_sum_avg_last_13_matches IS cluster2) AND (diff_team_score_xG_avg_last_9_matches IS cluster2) AND (diff_team_score_xG_sum_last_13_matches IS cluster2) AND (diff_team_progressive_passes_sum_last_11_matches IS cluster2) AND (diff_team_score_xG_avg_last_7_matches IS cluster2) AND (diff_team_attacking_third_touches_sum_last_15_matches IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (diff_team_penalty_area_touches_avg_last_15_matches IS cluster3) AND (diff_team_momentum_sum_avg_last_15_matches IS cluster3) AND (diff_team_score_xG_sum_last_15_matches IS cluster3) AND (diff_team_momentum_sum_sum_last_7_matches IS cluster3) AND (diff_team_attacking_third_touches_avg_last_13_matches IS cluster3) AND (diff_team_momentum_sum_sum_last_9_matches IS cluster3) AND (diff_team_momentum_sum_avg_last_11_matches IS cluster3) AND (diff_team_penalty_area_touches_sum_last_7_matches IS cluster3) AND (diff_team_carries_into_the_penalty_area_sum_last_15_matches IS cluster3) AND (diff_team_penalty_area_touches_avg_last_13_matches IS cluster3) AND (diff_team_points_sum_last_15_matches IS cluster3) AND (diff_team_points_sum_last_13_matches IS cluster3) AND (diff_team_momentum_count_avg_last_7_matches IS cluster3) AND (diff_team_shots_on_target_avg_last_13_matches IS cluster3) AND (diff_team_carries_into_the_penalty_area_sum_last_13_matches IS cluster3) AND (diff_team_attacking_third_touches_sum_last_11_matches IS cluster3) AND (diff_team_momentum_sum_avg_last_13_matches IS cluster3) AND (diff_team_score_xG_avg_last_9_matches IS cluster3) AND (diff_team_score_xG_sum_last_13_matches IS cluster3) AND (diff_team_progressive_passes_sum_last_11_matches IS cluster3) AND (diff_team_score_xG_avg_last_7_matches IS cluster3) AND (diff_team_attacking_third_touches_sum_last_15_matches IS cluster3) THEN (OUTPUT IS fun3)"
FS.add_rules([RULE1, RULE2, RULE3])

FS.set_output_function('fun1', '0.821149+0.041991*diff_team_penalty_area_touches_avg_last_15_matches+-0.005325*diff_team_momentum_sum_avg_last_15_matches+-0.407703*diff_team_score_xG_sum_last_15_matches+-0.026127*diff_team_momentum_sum_sum_last_7_matches+0.009096*diff_team_attacking_third_touches_avg_last_13_matches+-0.000889*diff_team_momentum_sum_sum_last_9_matches+0.292787*diff_team_momentum_sum_avg_last_11_matches+-0.034059*diff_team_penalty_area_touches_sum_last_7_matches+-0.05743*diff_team_carries_into_the_penalty_area_sum_last_15_matches+-0.353928*diff_team_penalty_area_touches_avg_last_13_matches+0.357979*diff_team_points_sum_last_15_matches+0.052722*diff_team_points_sum_last_13_matches+6.802039*diff_team_momentum_count_avg_last_7_matches+-1.655488*diff_team_shots_on_target_avg_last_13_matches+0.064609*diff_team_carries_into_the_penalty_area_sum_last_13_matches+-0.0003*diff_team_attacking_third_touches_sum_last_11_matches+0.016899*diff_team_momentum_sum_avg_last_13_matches+-2.866977*diff_team_score_xG_avg_last_9_matches+-0.474725*diff_team_score_xG_sum_last_13_matches+0.090106*diff_team_progressive_passes_sum_last_11_matches+5.394128*diff_team_score_xG_avg_last_7_matches+-0.004706*diff_team_attacking_third_touches_sum_last_15_matches')
FS.set_output_function('fun2', '1.00255+-0.425211*diff_team_penalty_area_touches_avg_last_15_matches+-0.00072*diff_team_momentum_sum_avg_last_15_matches+0.018229*diff_team_score_xG_sum_last_15_matches+-0.02756*diff_team_momentum_sum_sum_last_7_matches+0.006029*diff_team_attacking_third_touches_avg_last_13_matches+-0.000183*diff_team_momentum_sum_sum_last_9_matches+0.294541*diff_team_momentum_sum_avg_last_11_matches+-0.052946*diff_team_penalty_area_touches_sum_last_7_matches+-0.083909*diff_team_carries_into_the_penalty_area_sum_last_15_matches+0.034415*diff_team_penalty_area_touches_avg_last_13_matches+0.141499*diff_team_points_sum_last_15_matches+0.246437*diff_team_points_sum_last_13_matches+6.833981*diff_team_momentum_count_avg_last_7_matches+-1.707266*diff_team_shots_on_target_avg_last_13_matches+0.087905*diff_team_carries_into_the_penalty_area_sum_last_13_matches+-0.004183*diff_team_attacking_third_touches_sum_last_11_matches+0.017673*diff_team_momentum_sum_avg_last_13_matches+-5.39614*diff_team_score_xG_avg_last_9_matches+-0.936955*diff_team_score_xG_sum_last_13_matches+0.088771*diff_team_progressive_passes_sum_last_11_matches+9.251331*diff_team_score_xG_avg_last_7_matches+-0.00187*diff_team_attacking_third_touches_sum_last_15_matches')
FS.set_output_function('fun3', '1.055168+-0.285496*diff_team_penalty_area_touches_avg_last_15_matches+0.004127*diff_team_momentum_sum_avg_last_15_matches+0.365708*diff_team_score_xG_sum_last_15_matches+-0.0283*diff_team_momentum_sum_sum_last_7_matches+0.087947*diff_team_attacking_third_touches_avg_last_13_matches+-0.000146*diff_team_momentum_sum_sum_last_9_matches+0.290107*diff_team_momentum_sum_avg_last_11_matches+-0.060494*diff_team_penalty_area_touches_sum_last_7_matches+-0.146998*diff_team_carries_into_the_penalty_area_sum_last_15_matches+-0.246005*diff_team_penalty_area_touches_avg_last_13_matches+0.001661*diff_team_points_sum_last_15_matches+0.334251*diff_team_points_sum_last_13_matches+7.017907*diff_team_momentum_count_avg_last_7_matches+-0.759023*diff_team_shots_on_target_avg_last_13_matches+0.183381*diff_team_carries_into_the_penalty_area_sum_last_13_matches+-0.004899*diff_team_attacking_third_touches_sum_last_11_matches+0.009332*diff_team_momentum_sum_avg_last_13_matches+-7.262174*diff_team_score_xG_avg_last_9_matches+-1.025813*diff_team_score_xG_sum_last_13_matches+0.085898*diff_team_progressive_passes_sum_last_11_matches+9.627785*diff_team_score_xG_avg_last_7_matches+-0.00396*diff_team_attacking_third_touches_sum_last_15_matches')

FS_1 = FuzzySet(function=Gaussian_MF(-8.932903, 21.134833), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(-1.674164, 24.021394), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(9.376183, 19.127428), term='cluster3')
MF_diff_team_penalty_area_touches_avg_last_15_matches = LinguisticVariable([FS_1, FS_2, FS_3], concept='diff_team_penalty_area_touches_avg_last_15_matches' , universe_of_discourse=(-26.266666666666666, 22.4))
FS.add_linguistic_variable('diff_team_penalty_area_touches_avg_last_15_matches', MF_diff_team_penalty_area_touches_avg_last_15_matches)

FS_4 = FuzzySet(function=Gaussian_MF(-505.096644, 1298.464953), term='cluster1')
FS_5 = FuzzySet(function=Gaussian_MF(-76.797030, 1897.411271), term='cluster2')
FS_6 = FuzzySet(function=Gaussian_MF(549.614157, 1309.282879), term='cluster3')
MF_diff_team_momentum_sum_avg_last_15_matches = LinguisticVariable([FS_4, FS_5, FS_6], concept='diff_team_momentum_sum_avg_last_15_matches' , universe_of_discourse=(-1729.2666666666664, 1578.4666666666667))
FS.add_linguistic_variable('diff_team_momentum_sum_avg_last_15_matches', MF_diff_team_momentum_sum_avg_last_15_matches)

FS_7 = FuzzySet(function=Gaussian_MF(-9.415540, 20.365721), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(-3.551691, 20.900636), term='cluster2')
FS_9 = FuzzySet(function=Gaussian_MF(12.034434, 20.616999), term='cluster3')
MF_diff_team_score_xG_sum_last_15_matches = LinguisticVariable([FS_7, FS_8, FS_9], concept='diff_team_score_xG_sum_last_15_matches' , universe_of_discourse=(-26.999999999999993, 28.200000000000003))
FS.add_linguistic_variable('diff_team_score_xG_sum_last_15_matches', MF_diff_team_score_xG_sum_last_15_matches)

FS_10 = FuzzySet(function=Gaussian_MF(-6729.251444, 6328.892528), term='cluster1')
FS_11 = FuzzySet(function=Gaussian_MF(-202.396271, 5975.305523), term='cluster2')
FS_12 = FuzzySet(function=Gaussian_MF(5773.689866, 6694.047467), term='cluster3')
MF_diff_team_momentum_sum_sum_last_7_matches = LinguisticVariable([FS_10, FS_11, FS_12], concept='diff_team_momentum_sum_sum_last_7_matches' , universe_of_discourse=(-13653.0, 12034.0))
FS.add_linguistic_variable('diff_team_momentum_sum_sum_last_7_matches', MF_diff_team_momentum_sum_sum_last_7_matches)

FS_13 = FuzzySet(function=Gaussian_MF(-57.838038, 119.560070), term='cluster1')
FS_14 = FuzzySet(function=Gaussian_MF(5.283667, 122.888019), term='cluster2')
FS_15 = FuzzySet(function=Gaussian_MF(56.728649, 122.744375), term='cluster3')
MF_diff_team_attacking_third_touches_avg_last_13_matches = LinguisticVariable([FS_13, FS_14, FS_15], concept='diff_team_attacking_third_touches_avg_last_13_matches' , universe_of_discourse=(-158.53846153846155, 146.6153846153846))
FS.add_linguistic_variable('diff_team_attacking_third_touches_avg_last_13_matches', MF_diff_team_attacking_third_touches_avg_last_13_matches)

FS_16 = FuzzySet(function=Gaussian_MF(-8514.886308, 6866.470493), term='cluster1')
FS_17 = FuzzySet(function=Gaussian_MF(-660.863494, 6697.476777), term='cluster2')
FS_18 = FuzzySet(function=Gaussian_MF(8302.110551, 8960.959884), term='cluster3')
MF_diff_team_momentum_sum_sum_last_9_matches = LinguisticVariable([FS_16, FS_17, FS_18], concept='diff_team_momentum_sum_sum_last_9_matches' , universe_of_discourse=(-16382.0, 16109.0))
FS.add_linguistic_variable('diff_team_momentum_sum_sum_last_9_matches', MF_diff_team_momentum_sum_sum_last_9_matches)

FS_19 = FuzzySet(function=Gaussian_MF(-616.280726, 1244.159821), term='cluster1')
FS_20 = FuzzySet(function=Gaussian_MF(44.691687, 1540.709100), term='cluster2')
FS_21 = FuzzySet(function=Gaussian_MF(832.886744, 1106.935106), term='cluster3')
MF_diff_team_momentum_sum_avg_last_11_matches = LinguisticVariable([FS_19, FS_20, FS_21], concept='diff_team_momentum_sum_avg_last_11_matches' , universe_of_discourse=(-1634.272727272727, 1803.363636363636))
FS.add_linguistic_variable('diff_team_momentum_sum_avg_last_11_matches', MF_diff_team_momentum_sum_avg_last_11_matches)

FS_22 = FuzzySet(function=Gaussian_MF(-88.190214, 124.591139), term='cluster1')
FS_23 = FuzzySet(function=Gaussian_MF(3.974013, 101.442292), term='cluster2')
FS_24 = FuzzySet(function=Gaussian_MF(98.186836, 108.865509), term='cluster3')
MF_diff_team_penalty_area_touches_sum_last_7_matches = LinguisticVariable([FS_22, FS_23, FS_24], concept='diff_team_penalty_area_touches_sum_last_7_matches' , universe_of_discourse=(-189.0, 182.0))
FS.add_linguistic_variable('diff_team_penalty_area_touches_sum_last_7_matches', MF_diff_team_penalty_area_touches_sum_last_7_matches)

FS_25 = FuzzySet(function=Gaussian_MF(-52.639620, 88.905952), term='cluster1')
FS_26 = FuzzySet(function=Gaussian_MF(-14.902002, 89.258973), term='cluster2')
FS_27 = FuzzySet(function=Gaussian_MF(56.467467, 82.834565), term='cluster3')
MF_diff_team_carries_into_the_penalty_area_sum_last_15_matches = LinguisticVariable([FS_25, FS_26, FS_27], concept='diff_team_carries_into_the_penalty_area_sum_last_15_matches' , universe_of_discourse=(-119.0, 123.0))
FS.add_linguistic_variable('diff_team_carries_into_the_penalty_area_sum_last_15_matches', MF_diff_team_carries_into_the_penalty_area_sum_last_15_matches)

FS_28 = FuzzySet(function=Gaussian_MF(-8.894687, 19.827861), term='cluster1')
FS_29 = FuzzySet(function=Gaussian_MF(3.112310, 17.388127), term='cluster2')
FS_30 = FuzzySet(function=Gaussian_MF(8.000710, 19.322515), term='cluster3')
MF_diff_team_penalty_area_touches_avg_last_13_matches = LinguisticVariable([FS_28, FS_29, FS_30], concept='diff_team_penalty_area_touches_avg_last_13_matches' , universe_of_discourse=(-26.846153846153847, 21.076923076923077))
FS.add_linguistic_variable('diff_team_penalty_area_touches_avg_last_13_matches', MF_diff_team_penalty_area_touches_avg_last_13_matches)

FS_31 = FuzzySet(function=Gaussian_MF(-9.129237, 36.867351), term='cluster1')
FS_32 = FuzzySet(function=Gaussian_MF(-9.564677, 44.109247), term='cluster2')
FS_33 = FuzzySet(function=Gaussian_MF(13.557838, 25.396539), term='cluster3')
MF_diff_team_points_sum_last_15_matches = LinguisticVariable([FS_31, FS_32, FS_33], concept='diff_team_points_sum_last_15_matches' , universe_of_discourse=(-34.0, 34.0))
FS.add_linguistic_variable('diff_team_points_sum_last_15_matches', MF_diff_team_points_sum_last_15_matches)

FS_34 = FuzzySet(function=Gaussian_MF(-11.276238, 26.136040), term='cluster1')
# FS_35 = FuzzySet(function=Gaussian_MF(-1.938335, 40.511372), term='cluster2')
FS_36 = FuzzySet(function=Gaussian_MF(10.228679, 22.479756), term='cluster3')
MF_diff_team_points_sum_last_13_matches = LinguisticVariable([FS_34, FS_36], concept='diff_team_points_sum_last_13_matches' , universe_of_discourse=(-29.0, 29.0))
FS.add_linguistic_variable('diff_team_points_sum_last_13_matches', MF_diff_team_points_sum_last_13_matches)

FS_37 = FuzzySet(function=Gaussian_MF(-25.637710, 27.838440), term='cluster1')
FS_38 = FuzzySet(function=Gaussian_MF(-0.434894, 24.836469), term='cluster2')
FS_39 = FuzzySet(function=Gaussian_MF(22.015444, 29.523401), term='cluster3')
MF_diff_team_momentum_count_avg_last_7_matches = LinguisticVariable([FS_37, FS_38, FS_39], concept='diff_team_momentum_count_avg_last_7_matches' , universe_of_discourse=(-51.42857142857143, 48.57142857142857))
FS.add_linguistic_variable('diff_team_momentum_count_avg_last_7_matches', MF_diff_team_momentum_count_avg_last_7_matches)

FS_40 = FuzzySet(function=Gaussian_MF(-1.231331, 3.589630), term='cluster1')
FS_41 = FuzzySet(function=Gaussian_MF(0.031680, 3.911577), term='cluster2')
FS_42 = FuzzySet(function=Gaussian_MF(1.817947, 3.440456), term='cluster3')
MF_diff_team_shots_on_target_avg_last_13_matches = LinguisticVariable([FS_40, FS_41, FS_42], concept='diff_team_shots_on_target_avg_last_13_matches' , universe_of_discourse=(-4.076923076923077, 4.076923076923077))
FS.add_linguistic_variable('diff_team_shots_on_target_avg_last_13_matches', MF_diff_team_shots_on_target_avg_last_13_matches)

FS_43 = FuzzySet(function=Gaussian_MF(-40.258484, 75.323974), term='cluster1')
FS_44 = FuzzySet(function=Gaussian_MF(-20.134404, 71.937518), term='cluster2')
FS_45 = FuzzySet(function=Gaussian_MF(50.078887, 84.074229), term='cluster3')
MF_diff_team_carries_into_the_penalty_area_sum_last_13_matches = LinguisticVariable([FS_43, FS_44, FS_45], concept='diff_team_carries_into_the_penalty_area_sum_last_13_matches' , universe_of_discourse=(-101.0, 112.0))
FS.add_linguistic_variable('diff_team_carries_into_the_penalty_area_sum_last_13_matches', MF_diff_team_carries_into_the_penalty_area_sum_last_13_matches)

FS_46 = FuzzySet(function=Gaussian_MF(-694.068146, 1296.596049), term='cluster1')
FS_47 = FuzzySet(function=Gaussian_MF(193.374201, 1366.443419), term='cluster2')
FS_48 = FuzzySet(function=Gaussian_MF(785.259992, 1035.065134), term='cluster3')
MF_diff_team_attacking_third_touches_sum_last_11_matches = LinguisticVariable([FS_46, FS_47, FS_48], concept='diff_team_attacking_third_touches_sum_last_11_matches' , universe_of_discourse=(-1872.0, 1679.0))
FS.add_linguistic_variable('diff_team_attacking_third_touches_sum_last_11_matches', MF_diff_team_attacking_third_touches_sum_last_11_matches)

FS_49 = FuzzySet(function=Gaussian_MF(-473.331999, 1288.918764), term='cluster1')
FS_50 = FuzzySet(function=Gaussian_MF(143.995420, 1280.342865), term='cluster2')
FS_51 = FuzzySet(function=Gaussian_MF(520.770329, 1362.366255), term='cluster3')
MF_diff_team_momentum_sum_avg_last_13_matches = LinguisticVariable([FS_49, FS_50, FS_51], concept='diff_team_momentum_sum_avg_last_13_matches' , universe_of_discourse=(-1638.153846153846, 1602.6923076923076))
FS.add_linguistic_variable('diff_team_momentum_sum_avg_last_13_matches', MF_diff_team_momentum_sum_avg_last_13_matches)

FS_52 = FuzzySet(function=Gaussian_MF(-0.776167, 1.036627), term='cluster1')
FS_53 = FuzzySet(function=Gaussian_MF(0.174051, 1.118593), term='cluster2')
FS_54 = FuzzySet(function=Gaussian_MF(0.848341, 1.449871), term='cluster3')
MF_diff_team_score_xG_avg_last_9_matches = LinguisticVariable([FS_52, FS_53, FS_54], concept='diff_team_score_xG_avg_last_9_matches' , universe_of_discourse=(-1.6777777777777776, 1.9777777777777776))
FS.add_linguistic_variable('diff_team_score_xG_avg_last_9_matches', MF_diff_team_score_xG_avg_last_9_matches)

FS_55 = FuzzySet(function=Gaussian_MF(-9.219463, 15.245701), term='cluster1')
FS_56 = FuzzySet(function=Gaussian_MF(1.098223, 15.313565), term='cluster2')
FS_57 = FuzzySet(function=Gaussian_MF(11.168757, 18.385394), term='cluster3')
MF_diff_team_score_xG_sum_last_13_matches = LinguisticVariable([FS_55, FS_56, FS_57], concept='diff_team_score_xG_sum_last_13_matches' , universe_of_discourse=(-21.5, 24.7))
FS.add_linguistic_variable('diff_team_score_xG_sum_last_13_matches', MF_diff_team_score_xG_sum_last_13_matches)

FS_58 = FuzzySet(function=Gaussian_MF(-173.785911, 352.334765), term='cluster1')
FS_59 = FuzzySet(function=Gaussian_MF(38.929601, 485.731328), term='cluster2')
FS_60 = FuzzySet(function=Gaussian_MF(226.608154, 316.615807), term='cluster3')
MF_diff_team_progressive_passes_sum_last_11_matches = LinguisticVariable([FS_58, FS_59, FS_60], concept='diff_team_progressive_passes_sum_last_11_matches' , universe_of_discourse=(-495.0, 431.0))
FS.add_linguistic_variable('diff_team_progressive_passes_sum_last_11_matches', MF_diff_team_progressive_passes_sum_last_11_matches)

FS_61 = FuzzySet(function=Gaussian_MF(-0.917198, 1.396298), term='cluster1')
FS_62 = FuzzySet(function=Gaussian_MF(-0.082664, 1.304830), term='cluster2')
FS_63 = FuzzySet(function=Gaussian_MF(0.966619, 1.383775), term='cluster3')
MF_diff_team_score_xG_avg_last_7_matches = LinguisticVariable([FS_61, FS_62, FS_63], concept='diff_team_score_xG_avg_last_7_matches' , universe_of_discourse=(-1.8714285714285719, 2.0142857142857147))
FS.add_linguistic_variable('diff_team_score_xG_avg_last_7_matches', MF_diff_team_score_xG_avg_last_7_matches)

FS_64 = FuzzySet(function=Gaussian_MF(-973.392262, 1758.389431), term='cluster1')
FS_65 = FuzzySet(function=Gaussian_MF(12.257396, 2520.974779), term='cluster2')
FS_66 = FuzzySet(function=Gaussian_MF(891.043462, 1639.701162), term='cluster3')
MF_diff_team_attacking_third_touches_sum_last_15_matches = LinguisticVariable([FS_64, FS_65, FS_66], concept='diff_team_attacking_third_touches_sum_last_15_matches' , universe_of_discourse=(-2493.0, 2161.0))
FS.add_linguistic_variable('diff_team_attacking_third_touches_sum_last_15_matches', MF_diff_team_attacking_third_touches_sum_last_15_matches)


# end of automatically generated code #