# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (diff_team_penalty_area_touches_avg_last_15_matches IS cluster1) AND (diff_team_momentum_sum_avg_last_15_matches IS cluster1) AND (diff_team_score_xG_sum_last_15_matches IS cluster1) AND (diff_team_momentum_sum_sum_last_7_matches IS cluster1) AND (diff_team_attacking_third_touches_avg_last_13_matches IS cluster1) AND (diff_team_momentum_sum_sum_last_9_matches IS cluster1) AND (diff_team_momentum_sum_avg_last_11_matches IS cluster1) AND (diff_team_penalty_area_touches_sum_last_7_matches IS cluster1) AND (diff_team_carries_into_the_penalty_area_sum_last_15_matches IS cluster1) AND (diff_team_penalty_area_touches_avg_last_13_matches IS cluster1) AND (diff_team_points_sum_last_15_matches IS cluster1) AND (diff_team_points_sum_last_13_matches IS cluster1) AND (diff_team_momentum_count_avg_last_7_matches IS cluster1) AND (diff_team_shots_on_target_avg_last_13_matches IS cluster1) AND (diff_team_carries_into_the_penalty_area_sum_last_13_matches IS cluster1) AND (diff_team_attacking_third_touches_sum_last_11_matches IS cluster1) AND (diff_team_momentum_sum_avg_last_13_matches IS cluster1) AND (diff_team_score_xG_avg_last_9_matches IS cluster1) AND (diff_team_score_xG_sum_last_13_matches IS cluster1) AND (diff_team_progressive_passes_sum_last_11_matches IS cluster1) AND (diff_team_score_xG_avg_last_7_matches IS cluster1) AND (diff_team_attacking_third_touches_sum_last_15_matches IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (diff_team_penalty_area_touches_avg_last_15_matches IS cluster2) AND (diff_team_momentum_sum_avg_last_15_matches IS cluster2) AND (diff_team_score_xG_sum_last_15_matches IS cluster2) AND (diff_team_momentum_sum_sum_last_7_matches IS cluster2) AND (diff_team_attacking_third_touches_avg_last_13_matches IS cluster2) AND (diff_team_momentum_sum_sum_last_9_matches IS cluster2) AND (diff_team_momentum_sum_avg_last_11_matches IS cluster2) AND (diff_team_penalty_area_touches_sum_last_7_matches IS cluster2) AND (diff_team_carries_into_the_penalty_area_sum_last_15_matches IS cluster2) AND (diff_team_penalty_area_touches_avg_last_13_matches IS cluster2) AND (diff_team_points_sum_last_15_matches IS cluster2) AND (diff_team_momentum_count_avg_last_7_matches IS cluster2) AND (diff_team_shots_on_target_avg_last_13_matches IS cluster2) AND (diff_team_carries_into_the_penalty_area_sum_last_13_matches IS cluster2) AND (diff_team_attacking_third_touches_sum_last_11_matches IS cluster2) AND (diff_team_momentum_sum_avg_last_13_matches IS cluster2) AND (diff_team_score_xG_avg_last_9_matches IS cluster2) AND (diff_team_score_xG_sum_last_13_matches IS cluster2) AND (diff_team_progressive_passes_sum_last_11_matches IS cluster2) AND (diff_team_score_xG_avg_last_7_matches IS cluster2) AND (diff_team_attacking_third_touches_sum_last_15_matches IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (diff_team_penalty_area_touches_avg_last_15_matches IS cluster3) AND (diff_team_momentum_sum_avg_last_15_matches IS cluster3) AND (diff_team_score_xG_sum_last_15_matches IS cluster3) AND (diff_team_momentum_sum_sum_last_7_matches IS cluster3) AND (diff_team_attacking_third_touches_avg_last_13_matches IS cluster3) AND (diff_team_momentum_sum_sum_last_9_matches IS cluster3) AND (diff_team_momentum_sum_avg_last_11_matches IS cluster3) AND (diff_team_penalty_area_touches_sum_last_7_matches IS cluster3) AND (diff_team_carries_into_the_penalty_area_sum_last_15_matches IS cluster3) AND (diff_team_penalty_area_touches_avg_last_13_matches IS cluster3) AND (diff_team_points_sum_last_15_matches IS cluster3) AND (diff_team_points_sum_last_13_matches IS cluster3) AND (diff_team_momentum_count_avg_last_7_matches IS cluster3) AND (diff_team_shots_on_target_avg_last_13_matches IS cluster3) AND (diff_team_carries_into_the_penalty_area_sum_last_13_matches IS cluster3) AND (diff_team_attacking_third_touches_sum_last_11_matches IS cluster3) AND (diff_team_momentum_sum_avg_last_13_matches IS cluster3) AND (diff_team_score_xG_avg_last_9_matches IS cluster3) AND (diff_team_score_xG_sum_last_13_matches IS cluster3) AND (diff_team_progressive_passes_sum_last_11_matches IS cluster3) AND (diff_team_score_xG_avg_last_7_matches IS cluster3) AND (diff_team_attacking_third_touches_sum_last_15_matches IS cluster3) THEN (OUTPUT IS fun3)"
FS.add_rules([RULE1, RULE2, RULE3])

FS.set_output_function('fun1', '-0.058665+0.363859*diff_team_penalty_area_touches_avg_last_15_matches+-0.009429*diff_team_momentum_sum_avg_last_15_matches+0.314824*diff_team_score_xG_sum_last_15_matches+-0.033984*diff_team_momentum_sum_sum_last_7_matches+0.234271*diff_team_attacking_third_touches_avg_last_13_matches+8.7e-05*diff_team_momentum_sum_sum_last_9_matches+0.329706*diff_team_momentum_sum_avg_last_11_matches+0.063432*diff_team_penalty_area_touches_sum_last_7_matches+-0.013466*diff_team_carries_into_the_penalty_area_sum_last_15_matches+-0.735965*diff_team_penalty_area_touches_avg_last_13_matches+-0.103278*diff_team_points_sum_last_15_matches+0.020839*diff_team_points_sum_last_13_matches+7.390943*diff_team_momentum_count_avg_last_7_matches+-2.530267*diff_team_shots_on_target_avg_last_13_matches+-0.00548*diff_team_carries_into_the_penalty_area_sum_last_13_matches+-0.017681*diff_team_attacking_third_touches_sum_last_11_matches+0.006401*diff_team_momentum_sum_avg_last_13_matches+-8.019055*diff_team_score_xG_avg_last_9_matches+-0.336609*diff_team_score_xG_sum_last_13_matches+0.064249*diff_team_progressive_passes_sum_last_11_matches+11.607043*diff_team_score_xG_avg_last_7_matches+-0.000385*diff_team_attacking_third_touches_sum_last_15_matches')
FS.set_output_function('fun2', '-0.57837+-0.385064*diff_team_penalty_area_touches_avg_last_15_matches+-0.016235*diff_team_momentum_sum_avg_last_15_matches+0.765461*diff_team_score_xG_sum_last_15_matches+-0.033542*diff_team_momentum_sum_sum_last_7_matches+0.022088*diff_team_attacking_third_touches_avg_last_13_matches+0.000688*diff_team_momentum_sum_sum_last_9_matches+0.332334*diff_team_momentum_sum_avg_last_11_matches+0.028483*diff_team_penalty_area_touches_sum_last_7_matches+-0.034345*diff_team_carries_into_the_penalty_area_sum_last_15_matches+0.020989*diff_team_penalty_area_touches_avg_last_13_matches+-0.085347*diff_team_points_sum_last_15_matches+-0.009782*diff_team_points_sum_last_13_matches+7.173488*diff_team_momentum_count_avg_last_7_matches+-2.107166*diff_team_shots_on_target_avg_last_13_matches+0.014005*diff_team_carries_into_the_penalty_area_sum_last_13_matches+-0.010229*diff_team_attacking_third_touches_sum_last_11_matches+0.013983*diff_team_momentum_sum_avg_last_13_matches+-3.148928*diff_team_score_xG_avg_last_9_matches+-1.163757*diff_team_score_xG_sum_last_13_matches+0.052261*diff_team_progressive_passes_sum_last_11_matches+11.07957*diff_team_score_xG_avg_last_7_matches+0.00994*diff_team_attacking_third_touches_sum_last_15_matches')
FS.set_output_function('fun3', '-0.763096+-1.298387*diff_team_penalty_area_touches_avg_last_15_matches+-0.018045*diff_team_momentum_sum_avg_last_15_matches+1.070999*diff_team_score_xG_sum_last_15_matches+-0.032573*diff_team_momentum_sum_sum_last_7_matches+-0.08303*diff_team_attacking_third_touches_avg_last_13_matches+0.000607*diff_team_momentum_sum_sum_last_9_matches+0.324334*diff_team_momentum_sum_avg_last_11_matches+0.022364*diff_team_penalty_area_touches_sum_last_7_matches+0.108919*diff_team_carries_into_the_penalty_area_sum_last_15_matches+0.986489*diff_team_penalty_area_touches_avg_last_13_matches+-0.193183*diff_team_points_sum_last_15_matches+0.162142*diff_team_points_sum_last_13_matches+7.108921*diff_team_momentum_count_avg_last_7_matches+-2.88111*diff_team_shots_on_target_avg_last_13_matches+-0.149312*diff_team_carries_into_the_penalty_area_sum_last_13_matches+-0.005944*diff_team_attacking_third_touches_sum_last_11_matches+0.023255*diff_team_momentum_sum_avg_last_13_matches+1.199404*diff_team_score_xG_avg_last_9_matches+-1.694015*diff_team_score_xG_sum_last_13_matches+0.047327*diff_team_progressive_passes_sum_last_11_matches+8.433209*diff_team_score_xG_avg_last_7_matches+0.011212*diff_team_attacking_third_touches_sum_last_15_matches')

FS_1 = FuzzySet(function=Gaussian_MF(7.378306, 16.686555), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(3.097983, 15.659733), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(-7.285889, 17.028005), term='cluster3')
MF_diff_team_penalty_area_touches_avg_last_15_matches = LinguisticVariable([FS_1, FS_2, FS_3], concept='diff_team_penalty_area_touches_avg_last_15_matches' , universe_of_discourse=(-26.800000000000004, 26.0))
FS.add_linguistic_variable('diff_team_penalty_area_touches_avg_last_15_matches', MF_diff_team_penalty_area_touches_avg_last_15_matches)

FS_4 = FuzzySet(function=Gaussian_MF(361.122949, 1048.316577), term='cluster1')
FS_5 = FuzzySet(function=Gaussian_MF(-34.440210, 949.902782), term='cluster2')
FS_6 = FuzzySet(function=Gaussian_MF(-281.065823, 996.083744), term='cluster3')
MF_diff_team_momentum_sum_avg_last_15_matches = LinguisticVariable([FS_4, FS_5, FS_6], concept='diff_team_momentum_sum_avg_last_15_matches' , universe_of_discourse=(-1385.6, 1427.6000000000001))
FS.add_linguistic_variable('diff_team_momentum_sum_avg_last_15_matches', MF_diff_team_momentum_sum_avg_last_15_matches)

FS_7 = FuzzySet(function=Gaussian_MF(7.978604, 18.449928), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(-1.170139, 18.347527), term='cluster2')
FS_9 = FuzzySet(function=Gaussian_MF(-6.397883, 16.605141), term='cluster3')
MF_diff_team_score_xG_sum_last_15_matches = LinguisticVariable([FS_7, FS_8, FS_9], concept='diff_team_score_xG_sum_last_15_matches' , universe_of_discourse=(-22.200000000000003, 23.400000000000002))
FS.add_linguistic_variable('diff_team_score_xG_sum_last_15_matches', MF_diff_team_score_xG_sum_last_15_matches)

FS_10 = FuzzySet(function=Gaussian_MF(4652.261292, 4754.174004), term='cluster1')
FS_11 = FuzzySet(function=Gaussian_MF(360.764769, 4011.967512), term='cluster2')
FS_12 = FuzzySet(function=Gaussian_MF(-4483.222092, 5037.274535), term='cluster3')
MF_diff_team_momentum_sum_sum_last_7_matches = LinguisticVariable([FS_10, FS_11, FS_12], concept='diff_team_momentum_sum_sum_last_7_matches' , universe_of_discourse=(-10532.0, 10464.0))
FS.add_linguistic_variable('diff_team_momentum_sum_sum_last_7_matches', MF_diff_team_momentum_sum_sum_last_7_matches)

FS_13 = FuzzySet(function=Gaussian_MF(63.399141, 115.487181), term='cluster1')
FS_14 = FuzzySet(function=Gaussian_MF(14.173016, 118.818206), term='cluster2')
FS_15 = FuzzySet(function=Gaussian_MF(-38.402067, 148.992854), term='cluster3')
MF_diff_team_attacking_third_touches_avg_last_13_matches = LinguisticVariable([FS_13, FS_14, FS_15], concept='diff_team_attacking_third_touches_avg_last_13_matches' , universe_of_discourse=(-209.61538461538464, 184.30769230769232))
FS.add_linguistic_variable('diff_team_attacking_third_touches_avg_last_13_matches', MF_diff_team_attacking_third_touches_avg_last_13_matches)

FS_16 = FuzzySet(function=Gaussian_MF(6372.862292, 5413.213096), term='cluster1')
FS_17 = FuzzySet(function=Gaussian_MF(239.109623, 4822.221405), term='cluster2')
FS_18 = FuzzySet(function=Gaussian_MF(-6185.464222, 5173.506501), term='cluster3')
MF_diff_team_momentum_sum_sum_last_9_matches = LinguisticVariable([FS_16, FS_17, FS_18], concept='diff_team_momentum_sum_sum_last_9_matches' , universe_of_discourse=(-13018.0, 13480.0))
FS.add_linguistic_variable('diff_team_momentum_sum_sum_last_9_matches', MF_diff_team_momentum_sum_sum_last_9_matches)

FS_19 = FuzzySet(function=Gaussian_MF(536.531383, 721.050924), term='cluster1')
FS_20 = FuzzySet(function=Gaussian_MF(110.809938, 817.723012), term='cluster2')
FS_21 = FuzzySet(function=Gaussian_MF(-485.808638, 760.171007), term='cluster3')
MF_diff_team_momentum_sum_avg_last_11_matches = LinguisticVariable([FS_19, FS_20, FS_21], concept='diff_team_momentum_sum_avg_last_11_matches' , universe_of_discourse=(-1372.3636363636365, 1410.3636363636365))
FS.add_linguistic_variable('diff_team_momentum_sum_avg_last_11_matches', MF_diff_team_momentum_sum_avg_last_11_matches)

FS_22 = FuzzySet(function=Gaussian_MF(80.891906, 111.775452), term='cluster1')
FS_23 = FuzzySet(function=Gaussian_MF(-0.378948, 89.373529), term='cluster2')
FS_24 = FuzzySet(function=Gaussian_MF(-70.400062, 104.787072), term='cluster3')
MF_diff_team_penalty_area_touches_sum_last_7_matches = LinguisticVariable([FS_22, FS_23, FS_24], concept='diff_team_penalty_area_touches_sum_last_7_matches' , universe_of_discourse=(-185.0, 195.0))
FS.add_linguistic_variable('diff_team_penalty_area_touches_sum_last_7_matches', MF_diff_team_penalty_area_touches_sum_last_7_matches)

FS_25 = FuzzySet(function=Gaussian_MF(51.019887, 89.115703), term='cluster1')
FS_26 = FuzzySet(function=Gaussian_MF(14.718886, 90.889267), term='cluster2')
FS_27 = FuzzySet(function=Gaussian_MF(-47.007749, 92.276284), term='cluster3')
MF_diff_team_carries_into_the_penalty_area_sum_last_15_matches = LinguisticVariable([FS_25, FS_26, FS_27], concept='diff_team_carries_into_the_penalty_area_sum_last_15_matches' , universe_of_discourse=(-116.0, 124.0))
FS.add_linguistic_variable('diff_team_carries_into_the_penalty_area_sum_last_15_matches', MF_diff_team_carries_into_the_penalty_area_sum_last_15_matches)

FS_28 = FuzzySet(function=Gaussian_MF(6.402654, 17.518116), term='cluster1')
FS_29 = FuzzySet(function=Gaussian_MF(1.031189, 14.447267), term='cluster2')
FS_30 = FuzzySet(function=Gaussian_MF(-6.196095, 19.679055), term='cluster3')
MF_diff_team_penalty_area_touches_avg_last_13_matches = LinguisticVariable([FS_28, FS_29, FS_30], concept='diff_team_penalty_area_touches_avg_last_13_matches' , universe_of_discourse=(-29.461538461538463, 24.53846153846154))
FS.add_linguistic_variable('diff_team_penalty_area_touches_avg_last_13_matches', MF_diff_team_penalty_area_touches_avg_last_13_matches)

FS_31 = FuzzySet(function=Gaussian_MF(9.076746, 25.013148), term='cluster1')
FS_32 = FuzzySet(function=Gaussian_MF(4.664924, 29.092261), term='cluster2')
FS_33 = FuzzySet(function=Gaussian_MF(-8.131914, 37.480274), term='cluster3')
MF_diff_team_points_sum_last_15_matches = LinguisticVariable([FS_31, FS_32, FS_33], concept='diff_team_points_sum_last_15_matches' , universe_of_discourse=(-28.0, 27.0))
FS.add_linguistic_variable('diff_team_points_sum_last_15_matches', MF_diff_team_points_sum_last_15_matches)

FS_34 = FuzzySet(function=Gaussian_MF(9.101313, 23.010304), term='cluster1')
# FS_35 = FuzzySet(function=Gaussian_MF(4.055534, 34.629846), term='cluster2')
FS_36 = FuzzySet(function=Gaussian_MF(-8.077516, 31.115542), term='cluster3')
MF_diff_team_points_sum_last_13_matches = LinguisticVariable([FS_34, FS_36], concept='diff_team_points_sum_last_13_matches' , universe_of_discourse=(-27.0, 26.0))
FS.add_linguistic_variable('diff_team_points_sum_last_13_matches', MF_diff_team_points_sum_last_13_matches)

FS_37 = FuzzySet(function=Gaussian_MF(18.133462, 21.073773), term='cluster1')
FS_38 = FuzzySet(function=Gaussian_MF(1.685158, 21.330911), term='cluster2')
FS_39 = FuzzySet(function=Gaussian_MF(-19.961284, 25.555008), term='cluster3')
MF_diff_team_momentum_count_avg_last_7_matches = LinguisticVariable([FS_37, FS_38, FS_39], concept='diff_team_momentum_count_avg_last_7_matches' , universe_of_discourse=(-44.42857142857143, 39.14285714285714))
FS.add_linguistic_variable('diff_team_momentum_count_avg_last_7_matches', MF_diff_team_momentum_count_avg_last_7_matches)

FS_40 = FuzzySet(function=Gaussian_MF(1.647888, 4.110720), term='cluster1')
FS_41 = FuzzySet(function=Gaussian_MF(0.291212, 2.823556), term='cluster2')
FS_42 = FuzzySet(function=Gaussian_MF(-1.226751, 3.730397), term='cluster3')
MF_diff_team_shots_on_target_avg_last_13_matches = LinguisticVariable([FS_40, FS_41, FS_42], concept='diff_team_shots_on_target_avg_last_13_matches' , universe_of_discourse=(-5.230769230769232, 5.153846153846153))
FS.add_linguistic_variable('diff_team_shots_on_target_avg_last_13_matches', MF_diff_team_shots_on_target_avg_last_13_matches)

FS_43 = FuzzySet(function=Gaussian_MF(39.314094, 75.513558), term='cluster1')
FS_44 = FuzzySet(function=Gaussian_MF(15.169932, 73.250945), term='cluster2')
FS_45 = FuzzySet(function=Gaussian_MF(-43.684135, 86.761020), term='cluster3')
MF_diff_team_carries_into_the_penalty_area_sum_last_13_matches = LinguisticVariable([FS_43, FS_44, FS_45], concept='diff_team_carries_into_the_penalty_area_sum_last_13_matches' , universe_of_discourse=(-105.0, 109.0))
FS.add_linguistic_variable('diff_team_carries_into_the_penalty_area_sum_last_13_matches', MF_diff_team_carries_into_the_penalty_area_sum_last_13_matches)

FS_46 = FuzzySet(function=Gaussian_MF(839.364634, 1155.645826), term='cluster1')
FS_47 = FuzzySet(function=Gaussian_MF(80.383324, 1231.782371), term='cluster2')
FS_48 = FuzzySet(function=Gaussian_MF(-717.104580, 1226.129485), term='cluster3')
MF_diff_team_attacking_third_touches_sum_last_11_matches = LinguisticVariable([FS_46, FS_47, FS_48], concept='diff_team_attacking_third_touches_sum_last_11_matches' , universe_of_discourse=(-2170.0, 2048.0))
FS.add_linguistic_variable('diff_team_attacking_third_touches_sum_last_11_matches', MF_diff_team_attacking_third_touches_sum_last_11_matches)

FS_49 = FuzzySet(function=Gaussian_MF(401.589971, 943.498054), term='cluster1')
FS_50 = FuzzySet(function=Gaussian_MF(146.231862, 889.421889), term='cluster2')
FS_51 = FuzzySet(function=Gaussian_MF(-279.845199, 1084.561354), term='cluster3')
MF_diff_team_momentum_sum_avg_last_13_matches = LinguisticVariable([FS_49, FS_50, FS_51], concept='diff_team_momentum_sum_avg_last_13_matches' , universe_of_discourse=(-1469.230769230769, 1404.0769230769233))
FS.add_linguistic_variable('diff_team_momentum_sum_avg_last_13_matches', MF_diff_team_momentum_sum_avg_last_13_matches)

FS_52 = FuzzySet(function=Gaussian_MF(0.509872, 1.670398), term='cluster1')
FS_53 = FuzzySet(function=Gaussian_MF(-0.269880, 1.463842), term='cluster2')
FS_54 = FuzzySet(function=Gaussian_MF(-0.440131, 1.227231), term='cluster3')
MF_diff_team_score_xG_avg_last_9_matches = LinguisticVariable([FS_52, FS_53, FS_54], concept='diff_team_score_xG_avg_last_9_matches' , universe_of_discourse=(-1.5111111111111113, 1.5666666666666669))
FS.add_linguistic_variable('diff_team_score_xG_avg_last_9_matches', MF_diff_team_score_xG_avg_last_9_matches)

FS_55 = FuzzySet(function=Gaussian_MF(5.658733, 22.752974), term='cluster1')
FS_56 = FuzzySet(function=Gaussian_MF(-2.606897, 15.288818), term='cluster2')
FS_57 = FuzzySet(function=Gaussian_MF(-5.089414, 18.197884), term='cluster3')
MF_diff_team_score_xG_sum_last_13_matches = LinguisticVariable([FS_55, FS_56, FS_57], concept='diff_team_score_xG_sum_last_13_matches' , universe_of_discourse=(-20.6, 19.5))
FS.add_linguistic_variable('diff_team_score_xG_sum_last_13_matches', MF_diff_team_score_xG_sum_last_13_matches)

FS_58 = FuzzySet(function=Gaussian_MF(147.621459, 273.756766), term='cluster1')
FS_59 = FuzzySet(function=Gaussian_MF(-4.315552, 247.562620), term='cluster2')
FS_60 = FuzzySet(function=Gaussian_MF(-144.480569, 277.953389), term='cluster3')
MF_diff_team_progressive_passes_sum_last_11_matches = LinguisticVariable([FS_58, FS_59, FS_60], concept='diff_team_progressive_passes_sum_last_11_matches' , universe_of_discourse=(-451.0, 366.0))
FS.add_linguistic_variable('diff_team_progressive_passes_sum_last_11_matches', MF_diff_team_progressive_passes_sum_last_11_matches)

FS_61 = FuzzySet(function=Gaussian_MF(0.781649, 1.470523), term='cluster1')
FS_62 = FuzzySet(function=Gaussian_MF(-0.113081, 1.262690), term='cluster2')
FS_63 = FuzzySet(function=Gaussian_MF(-0.461228, 1.315479), term='cluster3')
MF_diff_team_score_xG_avg_last_7_matches = LinguisticVariable([FS_61, FS_62, FS_63], concept='diff_team_score_xG_avg_last_7_matches' , universe_of_discourse=(-1.957142857142857, 1.8714285714285714))
FS.add_linguistic_variable('diff_team_score_xG_avg_last_7_matches', MF_diff_team_score_xG_avg_last_7_matches)

FS_64 = FuzzySet(function=Gaussian_MF(806.384240, 1937.171893), term='cluster1')
FS_65 = FuzzySet(function=Gaussian_MF(158.020114, 1777.095751), term='cluster2')
FS_66 = FuzzySet(function=Gaussian_MF(-631.099872, 2028.987077), term='cluster3')
MF_diff_team_attacking_third_touches_sum_last_15_matches = LinguisticVariable([FS_64, FS_65, FS_66], concept='diff_team_attacking_third_touches_sum_last_15_matches' , universe_of_discourse=(-2956.0, 2959.0))
FS.add_linguistic_variable('diff_team_attacking_third_touches_sum_last_15_matches', MF_diff_team_attacking_third_touches_sum_last_15_matches)


# end of automatically generated code #